docs/api-reference.md
src/array_api_extra/__init__.py
src/array_api_extra/_funcs.py
tests/test_funcs.py

This would replace a private utility in SciPy.

ENH: a simple `cov`

---

docs/api-reference.md
src/array_api_extra/__init__.py
src/array_api_extra/_funcs.py
tests/test_funcs.py

ENH: add `sinc`

---

docs/api-reference.md
src/array_api_extra/__init__.py
src/array_api_extra/_funcs.py
tests/test_funcs.py

ENH: add `create_diagonal`

---

.github/workflows/ci.yml
README.md
codecov.yml
docs/contributing.md
pixi.lock
pyproject.toml
src/array_api_extra/_funcs.py
src/array_api_extra/_typing.py
tests/test_funcs.py

@jorenham could you review :) ?

TYP: adopt based{mypy, pyright}

---

.github/workflows/test-vendor.yml
.gitignore
README.md
docs/index.md
pixi.lock
pyproject.toml
src/array_api_extra/_funcs.py
src/array_api_extra/_lib/_compat.py
src/array_api_extra/_lib/_compat.pyi
src/array_api_extra/_lib/_utils.py
tests/test_funcs.py
tests/test_utils.py
vendor_tests/__init__.py
vendor_tests/_array_api_compat_vendor.py
vendor_tests/test_vendor.py

- Closes #6
- Blocked by #48
- Blocks implementation of `at` (https://github.com/data-apis/array-api-compat/pull/205)
Follow-up: vendoring hook in scipy

MAINT: depend on array-api-compat

---

src/array_api_extra/_funcs.py

anticipates https://github.com/data-apis/array-api/pull/868, https://github.com/data-apis/array-api-strict/pull/106
closes gh-49

BUG: fix sinc for torch

---

src/array_api_extra/_lib/_compat.pyi

Fix crash in https://github.com/scipy/scipy/pull/22062
https://app.circleci.com/jobs/github/scipy/scipy/107558
```
Traceback:
/home/circleci/.pyenv/versions/3.11.11/lib/python3.11/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
scipy/_lib/array_api_extra/_lib/_utils.py:1: in <module>
from . import _compat
E   ImportError: attempted relative import with no known parent package
=========================== short test summary info ============================
ERROR scipy/_lib/array_api_extra/_lib/_compat.py
ERROR scipy/_lib/array_api_extra/_lib/_typing.py
ERROR scipy/_lib/array_api_extra/_lib/_utils.py
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 3 errors in 3.33s …
```

Missing _lib/__init__.py

---

src/array_api_extra/__init__.py
src/array_api_extra/_funcs.py
src/array_api_extra/_lib/_compat.py
tests/test_funcs.py

closes gh-69
Add an `np.pad` replacement, as discussed at https://github.com/scipy/scipy/pull/22122/files#r1895558533

ENH: add `pad`

---

.github/workflows/ci.yml
docs/api-reference.md
docs/conf.py
pixi.lock
pyproject.toml
src/array_api_extra/__init__.py
src/array_api_extra/_funcs.py
src/array_api_extra/_lib/_compat.py
src/array_api_extra/_lib/_compat.pyi
src/array_api_extra/_lib/_typing.py
tests/test_at.py
vendor_tests/test_vendor.py

Implement a new `at(x, idx)` or `at(x)[idx]` function, mocking the syntax of [JAX's omonymous method](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html) .
This is propaedeutic to JAX support in libraries that support the Array API, e.g. scipy.
Moved from https://github.com/data-apis/array-api-compat/pull/205
- https://github.com/data-apis/array-api-compat/pull/205
- https://github.com/data-apis/array-api-compat/pull/207
- https://github.com/data-apis/array-api-compat/pull/211
- https://github.com/scipy/scipy/pull/22070

ENH: implement `at`

---

src/array_api_extra/_funcs.py
src/array_api_extra/_lib/_compat.pyi
src/array_api_extra/_lib/_utils.py

sklearn has not dropped 3.9 yet... it probably isn't a great idea to "unofficially" support Python 3.9 like this, but if it works it works I guess 🤷‍♂️ hopefully scikit-learn will cotton on to SPEC0 at some point

TYP: import annotations for sklearn

---

src/array_api_extra/_funcs.py

From https://github.com/scipy/scipy/pull/22226#issuecomment-2573824813

DOC: clarify `at()` patterns/antipatterns

---

pixi.lock
pyproject.toml
src/array_api_extra/_funcs.py
tests/test_funcs.py

Observed in https://github.com/scipy/scipy/pull/22226 : allow `pad_width` to be a tuple.

ENH: allow tuple pad_width in `pad`

---

README.md
docs/index.md

REL: officially adopt EffVer

---

docs/contributing.md

DOC: contributor docs for delegation

---

.github/workflows/ci.yml
docs/contributing.md
pixi.lock
pyproject.toml
src/array_api_extra/_lib/_utils/_compat.py
tests/conftest.py
tests/test_at.py

- Make `pixi run lint` much faster and allow running it on Windows (partially reverts #101)
- ~No need to explicitly specify lint environment anymore~
- Rename some environments for the sake of UX friendliness when a user runs `pixi run tests`

DEV: `pixi run lint` improvements

---

src/array_api_extra/_delegation.py
src/array_api_extra/_lib/_backends.py
tests/conftest.py
tests/test_at.py
tests/test_funcs.py
tests/test_testing.py
tests/test_utils.py

Change the "short summary info" at the end of a pytest run to be more informative re. which backends have triggered skips

TST: better pytest short summary info

---

src/array_api_extra/_delegation.py
src/array_api_extra/_lib/_funcs.py
tests/test_funcs.py

This is a blocker to porting https://github.com/scipy/scipy/pull/22308 to xpx, because jax.jit doesn't accept unhashable static arguments.
For clarity: this is just a quirk of https://github.com/scipy/scipy/pull/22308. You *can* pass a list parameter to `xpx.pad` inside jax.jit; you simply can't pass it if you are calling `pad = jax.jit(xpx.pad, static_argnames="pad_width")`, which is not something final users will typically do.

ENH: `pad`: `pad_width` can be any sequence

---

src/array_api_extra/_lib/_at.py

Backport from the much more complicated support for bool masks in JAX and Dask

MAINT: Simplify `at` implementation

---

docs/index.md
docs/testing-utils.md
pixi.lock
pyproject.toml
src/array_api_extra/_lib/_testing.py
src/array_api_extra/testing.py
tests/conftest.py
tests/test_at.py
tests/test_funcs.py
tests/test_testing.py
tests/test_utils.py

Porting of https://github.com/scipy/scipy/pull/22308, with additional support for Dask.

ENH: Test tools for jax.jit and dask

---

src/array_api_extra/_lib/_funcs.py
tests/test_funcs.py

Fix bug in setdiff1d when x2 is not 1-dimensional and assume_unique=True

BUG: `setdiff1d` vs. non-1d arrays

---

docs/conf.py
src/array_api_extra/_delegation.py
src/array_api_extra/_lib/_funcs.py
src/array_api_extra/_lib/_utils/_helpers.py
tests/test_funcs.py
tests/test_utils.py

Implement 2024.12 rules for `kron`, `isclose`, and `setdiff1d` for when a binary operation runs on an Array API object and a python scalar.
https://data-apis.org/array-api/draft/API_specification/type_promotion.html#mixing-arrays-with-python-scalars

ENH: Array API 2024.12 binary ops vs. Python scalars

---

pixi.lock
pyproject.toml
src/array_api_extra/_lib/_testing.py
tests/conftest.py
tests/test_at.py
tests/test_funcs.py
tests/test_testing.py
tests/test_utils.py

- Use `skip_xp_backend` when the library is Array API compliant, but with rightful limitations that make the functionality fail
- Use `xfail_xp_backend` when the failure is caused by non-compliance with the Array API. The test runs anyway; `pixi run tests` will exit 1 if there are any `XPASS` tests.

TST: `xfail_xp_backend`

---

docs/api-reference.md
docs/conf.py
src/array_api_extra/__init__.py
src/array_api_extra/_lib/_funcs.py
tests/test_funcs.py

`lazy_apply` benefits from this.

ENH: `broadcast_shapes`

---

docs/conf.py
pixi.lock
pyproject.toml
src/array_api_extra/_lib/_at.py
src/array_api_extra/_lib/_utils/_helpers.py
src/array_api_extra/_lib/_utils/_typing.py
src/array_api_extra/testing.py
tests/conftest.py

Various generic improvements backported from #141 and #86

MAINT: various backports and tweaks

---

src/array_api_extra/_lib/_funcs.py
src/array_api_extra/_lib/_utils/_helpers.py
tests/test_funcs.py
tests/test_helpers.py

ENH: `create_diagonal`: support broadcasting

---

src/array_api_extra/_lib/_at.py
tests/test_at.py

Closes #134
- When x is a dask array,
- and idx is a bool mask of the same shape as x,
- and y is a scalar,
- and copy=None,
don't perform the unnecessary extra step of writing back to `x` (which encroaches on https://github.com/dask/dask/issues/11722).
This PR works around a bug of Dask 2025.1.0. Starting from Dask 2025.2.0, this becomes a nice-to-have.

BUG: `at` should not force overwrite in Dask when copy=None

---

src/array_api_extra/testing.py
tests/test_testing.py

Working in scipy I realized that forcing the developer who writes the tests to `import <names> from <module>` can be extremely cumbersome - see for example `scipy.stats.tests.test_stats`.
This PR allows simply calling 
```python
import <module>
lazy_xp_modules = [<module>]
def test_<funcname>(xp):
<module>.<funcname>(...)
```

ENH: `lazy_xp_function` namespaces support

---

docs/api-reference.md
pixi.lock
pyproject.toml
src/array_api_extra/__init__.py
src/array_api_extra/_lib/_at.py
src/array_api_extra/_lib/_funcs.py
src/array_api_extra/_lib/_utils/_helpers.py
tests/test_at.py
tests/test_funcs.py
tests/test_helpers.py

Closes #14.
`scipy._lib._utils.lazywhere`, with revised UI and added support for jax.jit and Dask.

ENH: `apply_where` (migrate `lazywhere` from scipy)

---

pixi.lock
pyproject.toml
src/array_api_extra/_lib/_lazy.py
src/array_api_extra/_lib/_testing.py
tests/test_at.py
tests/test_funcs.py
tests/test_lazy.py

- Now dev environments match CI tests
- numpy in 'tests' environment (used by developers), 'docs', and 'lint' upgraded from 2.1 to 2.2

MAINT: general deps bump

---

pixi.lock
pyproject.toml

Without this, if you're on an Intel Mac like me, the tasks won't work properly (in fact, no tasks will show up).
Suprisingly, there is no warning.
To test this, I guess we can add macos-13 testing in Github Actions.
It's probably not be worth it, though (since this is a pure Python package anyways).

DEV: Configure pixi for Intel Macs

---

src/array_api_extra/_lib/_at.py
src/array_api_extra/_lib/_backends.py
src/array_api_extra/_lib/_funcs.py
src/array_api_extra/_lib/_utils/_helpers.py
tests/conftest.py
tests/test_at.py
tests/test_funcs.py
tests/test_helpers.py
tests/test_lazy.py
tests/test_testing.py

- Run all tests with array-api-strict with all optional capabilities disabled
- Add `nunique` support for unknown backends without `unique_counts` - for example, `marray` wrapping around JAX.
- Add `apply_where` support for unknown backends without boolean index assignment - again for example `marray` wrapping around JAX (but see https://github.com/jax-ml/jax/issues/27418) 
- Add `apply_where` support for sparse arrays
- https://github.com/jax-ml/jax/issues/27418
- https://github.com/data-apis/array-api-compat/pull/290
- https://github.com/mdhaber/marray/issues/99

ENH/TST: tougher restrictions on array_api_strict

---

pixi.lock
pyproject.toml
src/array_api_extra/_lib/_at.py
src/array_api_extra/_lib/_backends.py
src/array_api_extra/_lib/_testing.py
tests/conftest.py
tests/test_at.py
tests/test_funcs.py
tests/test_lazy.py
tests/test_testing.py

- On the `tests-cuda` and `dev-cuda` pixi environments, run all tests first on CPU and then on GPU:
- on JAX (before it was only on GPU)
- on PyTorch (before it was only on CPU)
- Work around PyTorch bug impacting `xpx.at` https://github.com/pytorch/pytorch/issues/150017

TST: run tests on CPU+GPU

---

pixi.lock
pyproject.toml

closes #197
I thought I should get with the times and learn pixi!
```
➜  array-api-extra git:(gh-197) pixi task list
Tasks that can run on this machine:
-----------------------------------
clean-vendor-compat, clean-vendor-extra, copy-vendor-compat, copy-vendor-extra, coverage, docs, ipython, lint, mypy, open-coverage, open-docs, pre-commit, pre-commit-install, pylint, pyright, tests, tests-ci, tests-cov, tests-vendor
- clean-vendor-compat Delete the existing vendored version of array-api-compat
- clean-vendor-extra Delete the existing vendored version of array-api-extra
- copy-vendor-compat Vendor a clean copy of array-api-compat
- copy-vendor-extra Vendor a clean copy of array-api-extra
- coverage        Generate test coverage html report
- docs            Build docs
- ipython …
```

DEV: add Pixi task descriptions

---

src/array_api_extra/_delegation.py
src/array_api_extra/_lib/__init__.py
src/array_api_extra/_lib/_backends.py
tests/conftest.py
tests/test_at.py
tests/test_funcs.py
tests/test_helpers.py
tests/test_lazy.py
tests/test_testing.py

Follow-up from https://github.com/data-apis/array-api-extra/pull/221#discussion_r2033668108
Do not use the `Backend` enum outside of testing.
This enum contains a lot of "backends" that are just variant duplicates, which is an artifact of using this enum to parametrize the `xp` fixture. Which is a decent hack for pytest, but which doesn't make any sense in the context of the dispatch system.
This also allows for quite a bit of simplification without adding any weight to the delegate module itself.

MAINT: Don't use `Backend` for delegation

---

tests/test_funcs.py

I'm observing random failures in Dask in this test.
The reason is that `xp_assert_equal()` is calling `dask.compute()` twice, which in turn rematerializes the graph from scratch twice - thus calling `np.empty` twice. That in turn occasionally returns differently dirty memory between `expect` and `actual`.

TST: flaky `test_single_axis` on Dask

---

codecov.yml

this avoids failing statuses on PRs due to having to wait for test-backends in unrelated areas of the codebase

DEV: disable codecov project status

---

src/array_api_extra/testing.py
tests/test_testing.py

scipy developers get confused by
`lazy_xp_function(func, allow_dask_compute=999)`
Allow writing
`lazy_xp_function(func, allow_dask_compute=True)`
instead.

ENH: `allow_dask_compute=True` instead of 999

---

pixi.lock
src/array_api_extra/__init__.py
src/array_api_extra/_lib/_utils/_compat.py
src/array_api_extra/_lib/_utils/_typing.py

- **DEV: bump version to 0.8.0.dev0**
- **update lock file**

DEV: bump version to 0.8.0.dev0

---

src/array_api_extra/_lib/_utils/_helpers.py
src/array_api_extra/testing.py

Follow-up to https://github.com/data-apis/array-api-extra/pull/284#pullrequestreview-2847583988
@rgommers

DOC: `autojit` notes

---

tests/test_testing.py

- group tests
- make test skips and mypy ignores less obnoxious
- check assertion messages
- don't rely on strict=False when xfailing
- Increase coverage for `xp_assert_less`
- test that `check_dtype=False`, `check_shape=False` don't disable anything else

TST: rework tests for `xp_assert_equal`

---

src/array_api_extra/_lib/_funcs.py
src/array_api_extra/_lib/_testing.py
src/array_api_extra/_lib/_utils/_helpers.py
tests/conftest.py
tests/test_funcs.py
tests/test_helpers.py
tests/test_lazy.py
tests/test_testing.py

- Add support for PyTorch `meta` device. Specifically, this PR fixes:
- `apply_where`
- `nunique`
- `_testing.xp_assert_equal`
- `_testing.xp_assert_close`
- `_testing.xp_assert_less`
- Test PyTorch input->output device propagation
- when input device is `meta` but default device is `cpu`;
- on pixi environments `tests_cuda` and `dev_cuda`, when input device is `cpu` but default device is `cuda`
XREF https://github.com/data-apis/array-api/issues/945

ENH: support PyTorch `device='meta'`

---

docs/api-reference.md
src/array_api_extra/__init__.py
src/array_api_extra/_delegation.py
src/array_api_extra/_lib/_funcs.py
tests/test_funcs.py

Fixes #305
Questions:
* What should the default output dtype be?  Currently, it's the default float type on Jax/PyTorch, or else float64.  Should I try to get the default float type on the platform: `xp.empty(()).dtype`?

ENH: add new function `one_hot`

---

pixi.lock
pyproject.toml

deps: pin array-api-strict<2.4

---

RELEASING.md
pixi.lock
src/array_api_extra/__init__.py

DEV: bump version to v0.9.0.dev0

---

.github/workflows/ci.yml
pixi.lock
pyproject.toml

Move the default Python version for backends to 3.13.
This is necessary for JAX, which has already dropped 3.10; others are expected to follow.
Test JAX 0.7.0 where possible.
Notable upgrades:
```
Platform: tests-backends:linux-64                                                   
~ C jax                                 0.6.0 pyhd8ed1ab_0                    ->  0.7.0 pyhd8ed1ab_0
~ C jaxlib                              0.6.0 cpu_py310hc96afab_0             ->  0.7.0 cpu_py313h9430eff_0
~ C python                              3.10.18 hd6af730_0_cpython            ->  3.13.7 h2b335a9_100_cp313
~ C scipy                               1.15.2 py310h1d65ade_0                ->  1.16.1 py313h11c21cd_1
Platform: tests-cuda:linux-64                                                       
~ C python …
```

TST: JAX 0.7.0

---

renovate.json

jax 0.7.0 and later is incompatible with Python 3.10.
jax.0.6.2 and later segfaults on CUDA. Note that CUDA is not in CI.
I've never tampered with renovate before so I'm not 100% sure about what I'm doing.

MAINT: renovate to skip JAX

---

src/array_api_extra/__init__.py
src/array_api_extra/_delegation.py
src/array_api_extra/_lib/_funcs.py

This merge request introduces the sinc delegate function (#100).
The `sinc` delegate function has been implemented.
I have checked its compatibility with all supported backends. Only PyDataSparse does not support this function.
CuPy has [extra parameters](https://docs.cupy.dev/en/stable/reference/generated/cupy.sinc.html), but its default behavior matches the expected behavior.
Available for feedback!

ENH: delegate `sinc` function

---

src/array_api_extra/__init__.py
src/array_api_extra/_delegation.py
src/array_api_extra/_lib/_funcs.py
tests/test_funcs.py

This merge request introduces the `atleast_nd` delegate function (#100).
Unlike other delegate functions, `atleast_nd` does not exist for all major backends. Instead, the functions `atleast_1d`, `atleast_2d`, and `atleast_3d` are available.
In this implementation, I use `getattr` to delegate when ndim is between 1 and 3. I’ve also added tests with ndim=3 to cover the full range.
Open to feedback!

ENH: `atleast_nd` delegation
